src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\CategoryRepository;


/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom de la catégorie ne peut pas être vide")
     * @Assert\Length(min=5, minMessage="Le nom de la catégorie doit comporter au minimum 5 caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="category")
     */
    private $Products;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="categories")
     */
    private $owner;

    public function __construct()
    {
        $this->Products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->Products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->Products->contains($product)) {
            $this->Products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->Products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom du produit est obligatoire")
     * @Assert\Length(min=3, max=255, minMessage="Le nom du produit doit avoir au moins 3 caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le prix du produit est obligatoire")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="Products")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le produit doit obligatoirement comporter une image")
     * @Assert\Url(message="L'image doit être importer uniquement sous forme d'URL et être valide")
     */
    private $mainPicture;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Le produit doit obligatoirement comporter une description")
     * @Assert\Length(min=20, minMessage="La description du produit doit avoir au moins 20 caractères")
     */
    private $shortDescription;

    //-----------------------Contrainte / Réguex de de données formulaire ---------------------------------
    // public static function loadValidatorMetadata(ClassMetadata $metaData)
    // {
    //     $metaData->addPropertyConstraints('name', [
    //         new Assert\NotBlank(['message' => "Le nom du produit est obligatoire"]),
    //         new Assert\Length(['min' => 3, 'max' => 255, 'minMessage' => "Le nom du produit doit faire plus de 3 charactères"])
    //     ]);
    //     $metaData->addPropertyConstraint('price', new Assert\NotBlank(['message' => "Le prix du produit est obligatoire"]));
    // }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(?string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(?string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Category;
use App\Form\DataTransformer\CentimesTransformer;
use App\Form\Type\PriceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('name', TextType::class, [
            'label' => 'Nom du produit',
            'attr' => ['placeholder' => 'Tapez le nom du produit'],
            'required' => false
        ])
            ->add('shortDescription', TextareaType::class, [
                'label' => 'Description courte',
                'attr' => ['placeholder' => 'Tapez une description courte'],
                'required' => false
            ])
            ->add('price', MoneyType::class, [
                'label' => 'Prix du produit ',
                'attr' => ['placeholder' => 'Tapez le prix du produit'],
                'divisor' => 100,
                'required' => false
            ])
            ->add('mainPicture', UrlType::class, [
                'label' => 'Image du produit',
                'attr' => ['placeholder' => "Tapez une URL d'image"],
                'required' => false
            ])
            ->add('category', EntityType::class, [
                'label' => 'Catégorie',
                'placeholder' => '-- Choisir une catégorie --',
                'class' => Category::class, // $option
                'choice_label' =>  function (Category $category) {
                    return strtoupper($category->getName());
                }, //'name'
            ]);


        // $builder->get('price')->addModelTransformer(new CentimesTransformer);

        // $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
        //     /** @var Product */
        //     $product = $event->getData();

        //     if ($product->getPrice() !== null) $product->setPrice($product->getPrice() * 100);
        // });

        // // post_set_data, pre_submit, submit, post_submit
        // $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
        //     $form = $event->getForm();

        //     /** @var Product */
        //     $product = $event->getData();


        //     if ($product->getPrice() !== null) $product->setPrice($product->getPrice() / 100);

        //     // if ($product->getId() === null) {

        //     //     $form->add('category', EntityType::class, [
        //     //         'label' => 'Catégorie',
        //     //         'placeholder' => '-- Choisir une catégorie --',
        //     //         'class' => Category::class, // $option
        //     //         'choice_label' =>  function (Category $category) {
        //     //             return strtoupper($category->getName());
        //     //         } //'name'

        //     //     ]);
        //     // }
        // });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Bezhanov\Faker\Provider\Placeholder;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class ProductController extends AbstractController
{
    #[Route('/{slug}', name: 'product_category', priority: -1)]
    public function category($slug, CategoryRepository $categoryRepository): Response
    {
        $category = $categoryRepository->findOneBy(['slug' => $slug]);
        if (!$category) throw $this->createNotFoundException("La categorie n'existe pas");

        return $this->render('product/category.html.twig', [
            'slug' => $slug,
            'category' => $category
        ]);
    }

    #[Route('/{category_slug}/{slug}', name: 'product_show')]
    public function show($slug, ProductRepository $productRepository)
    {

        $product = $productRepository->findOneBy(['slug' => $slug]);

        if (!$product) throw $this->createNotFoundException("Le produit n'existe pas");

        return $this->render('product/show.html.twig', ['product' => $product]);
    }

    #[Route('/admin/product/create', name: 'product_create')]
    public function create(FormFactoryInterface $formFactoryInterface, Request $request, SluggerInterface $slugger, EntityManagerInterface $em)
    {
        // $option = [];

        // foreach ($categoryRepository->findAll() as  $c) {
        //     $option[$c->getName()] = $c->getId();
        // }

        $product = new Product;
        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product->setSlug(strtolower($slugger->slug($product->getName())));
            // $product = new Product;
            // $product->setName($data['name'])
            //     ->setShortDescription($data['shortDescription'])
            //     ->setPrice($data['price'])
            //     ->setCategory($data['category']);
            $em->persist($product);
            $em->flush();

            // $url = $urlGenerator->generate('product_show', [
            //     'category_slug' => $product->getCategory()->getSlug(),
            //     'slug' => $product->getSlug()
            // ]);
            // $redirect = new RedirectResponse();

            return $this->redirectToRoute('product_show', [
                'category_slug' => $product->getCategory()->getSlug(),
                'slug' => $product->getSlug()
            ]);
        }
        $formView = $form->createView();

        return $this->render('product/create.html.twig', ['formView' => $formView]);
    }
    #[route('/admin/product/{id}/edit', name: 'product_edit')]
    public function edit($id, ProductRepository $productRepository, Request $request, EntityManagerInterface $em, SluggerInterface $slugger, ValidatorInterface $validator)
    {
        //---------------------------Début validator--------------------------------
        // $age = 100;
        // $client = [
        //     'nom' => 'Nardella',
        //     'prenom' => 'Victor',
        //     'voiture' => [
        //         'marque' => 'renault',
        //         'couleur' => ''
        //     ]
        // ];

        // $collection = new Collection([
        //     'nom' => new NotBlank(['message' => "Le nom ne doit pas êtres vide"]),
        //     'prenom' => [
        //         new NotBlank(['message' => "Le prenom ne doit pas être vide"]),
        //         new Length(['min' => 3, 'minMessage' => "Le prénom ne doit pas faire moins de 34 charactères"])
        //     ],
        //     'voiture' => new Collection([
        //         'marque' => new NotBlank(['message' => "La marque de la voiture est obligatoire"]),
        //         'couleur' => new NotBlank(['message' => "La couleur de la voiture est obligatoire"])
        //     ])
        // ]);

        // $resultat = $validator->validate($client, $collection);

        // $resultat = $validator->validate($age, [
        //     new LessThanOrEqual([
        //         'value' => 90,
        //         'message' => "L'âge doit être inférieur à {{compared_value}}, vous avez donné {{value}}"
        //     ]),
        //     new GreaterThan([
        //         'value' => 0,
        //         'message' => "L'âge doit être supérieur à 0"
        //     ])
        // ]); 


        // $product = new Product;

        // $resultat = $validator->validate($product);

        // if ($resultat->count() > 0) dd("ERREUR", $resultat);
        // dd('Tout est bon');


        $product = $productRepository->find($id);

        if (!$product) throw new NotFoundHttpException("Ce produit n'existe pas");

        $form = $this->createForm(ProductType::class, $product); // $form->setData($product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product->setSlug(strtolower($slugger->slug($product->getName())));
            $em->flush();

            return $this->redirectToRoute('product_show', [
                'category_slug' => $product->getCategory()->getSlug(),
                'slug' => $product->getSlug()
            ]);
        }

        $formView = $form->createView();

        return $this->render('product/edit.html.twig', ['product' => $product, 'formView' => $formView]);
    }
}

templates/product/category.html.twig
{% extends "base.html.twig" %} {% block title %} Catégorie : {{category.name}} {% endblock title %} {% block body %}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{path('homePage')}}">Accueil</a></li>
    <li class="breadcrumb-item active">{{category.name}}</li>
</ol>
<h2> Catégorie : {{category.name}}</h2>
<div class="row"> {% for i in category.products %}

    <div class="col-3">
        <div class="card">
            <img src="{{i.mainPicture}}" alt="img" class="img-fluid">
            <div class="card-body">
                <h4 class="card-title">{{i.name}} ({{i.price / 100}}€)</h4>
                <span class="badge rounded-pill bg-success">{{i.category.name}}</span>
                <p class="card-text">{{i.shortDescription}}</p>
                <a href="{{path('product_show', {'category_slug': i.category.slug, 'slug': i.slug})}}" class="btn btn-primary btn btn-sm ">Détails</a>
                <a href="# " class="btn btn-success btn-sm ">Ajouter</a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

{% endblock body %}

templates/product/create.html.twig
{% extends "base.html.twig" %} {% block title %} Création produit {% endblock title %} {% block body %}

<h1>Nouveau produit</h1>

{{form_start(formView)}}
<div class="row">
    <div class="col">
        {{form_row(formView.name)}}
        <div class="mt-3">{{form_row(formView.price)}}</div>
    </div>
    <div class="col">
        {{form_row(formView.mainPicture)}}
        <div class="mt-3">{{form_row(formView.category)}}</div>
        <div class="mt-3">{{form_row(formView.shortDescription)}}</div>
    </div>
</div>

<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Enregistrer</button> {{form_end(formView)}} {% endblock body %}

templates/product/edit.html.twig
{% extends "base.html.twig" %} {% block title %} Edition de {{product.name}} {% endblock title %} {% block body %}

<h1>Editer le produit : {{product.name}}</h1>

{{form_start(formView)}}
<div class="row">
    <div class="col">
        {{form_row(formView.name)}}
        <div class="mt-3">{{form_row(formView.price)}}</div>
    </div>
    <div class="col">
        {{form_row(formView.mainPicture)}}
        <div class="mt-3">{{form_row(formView.category)}}</div>
        <div class="mt-3">{{form_row(formView.shortDescription)}}</div>
    </div>
</div>

<button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Modifier</button> {{form_end(formView)}} {% endblock body %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/victo/Desktop/cours_ecommerce/src/Controller/ProductController.php'|file_link(0) }}">src/Controller/ProductController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/victo/Desktop/cours_ecommerce/templates/product/index.html.twig'|file_link(0) }}">templates/product/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/product/show.html.twig
{% extends "base.html.twig" %} {% block title %} Produit : {{product.name}} {% endblock title %} {% block body %}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{path('homePage')}}">Accueil</a></li>
    <li class="breadcrumb-item"><a href="{{path('product_category', {'slug': product.category.slug})}}">{{product.category.name}}</a></li>
    <li class="breadcrumb-item active">{{product.name}}</li>
</ol>
<h2>{{product.name}} ({{product.price / 100}}€)</h2>
<div class="row">
    <div class="col-4">
        <img class="img-fluid" src="{{product.mainPicture}}" alt="img_product">
    </div>
    <div class="col">
        <span class="badge rounded-pill bg-success">{{product.category.name}}</span>
        <p>{{product.shortDescription}}</p>
        <a href="#" class="btn btn-success btn-sm"><i class="fas fa-shopping-cart"></i>Ajouter au panier</a>
    </div>
</div>
{% endblock body %}